name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: make build

      - name: Run tests
        run: make test
